name: tax-reform-did-project

channels:
  - conda-forge
  - defaults

dependencies:
  # Core language
  - python=3.14.2

  # Data + analysis
  - numpy>=2.0
  - pandas>=2.0
  - scipy>=1.14

  # Econometrics / stats
  - statsmodels>=0.14

  # Visualization
  - matplotlib>=3.9
  - seaborn>=0.13

  # Notebook environment
  - jupyterlab
  - ipykernel
  - nbconvert

  - pip

  - pip:
      - nbmake